API_Catalogo/src/web/NSE.WebApp.MVC/Controllers/CatalogoController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NSE.WebApp.MVC.Services;

namespace NSE.WebApp.MVC.Controllers
{
    public class CatalogoController : MainController
    {
        private readonly ICatalogoService _catalogoService;

        public CatalogoController(ICatalogoService catalogoService)
        {
            _catalogoService = catalogoService;
        }

        [HttpGet]
        [Route("")]
        [Route("vitrine")]
        public async Task<IActionResult> Index()
        {
            var produtos = await _catalogoService.ObterTodos();

            return View(produtos);
        }

        [HttpGet]
        [Route("produto-detalhe/{id}")]
        public async Task<IActionResult> ProdutoDetalhe(Guid id)
        {
            var produto = await _catalogoService.ObterPorId(id);

            return View(produto);
        }
    }
}

API_Catalogo/src/web/NSE.WebApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - NerdStore Enterprise</title>
    
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
    <link href="~/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-4">
                        <a asp-action="Index" asp-controller="Catalogo" class="brand-wrap">
                            <img alt="Nerd Store Enterprise" class="logo" src="~/images/logo.png">
                        </a>   
                    </div>
                    
                    <div class="col-lg-9 col-sm-7 col-8 order-2 order-lg-3">
                        <div class="d-flex justify-content-end">
                            <div style="padding-right: 15px">
                                <a href="#" class="widget-header">
                                    <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                                    <span class="badge badge-pill badge-danger notify">0</span>
                                </a>
                            </div>
                            <div>
                                <partial name="_LoginPartial" />
                            </div>
                        </div>   
                    </div>   
                </div>   
            </div>   
        </section>    



    </header>
    <div style="min-height: 625px;">
            @RenderBody()
    </div>

    <footer class="section-footer border-top">
        <div class="container">
            <section class="footer-top padding-y">
                <div class="row">
                    <aside class="col-md-4">
                        <article class="mr-3">
                            <img src="~/images/logo.png" class="logo-footer">
                            <p class="mt-3">Um pequeno texto institucional da Nerd Store Enterprise.</p>
                            <div>
                                <a class="btn btn-icon btn-light" title="Facebook" target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-icon btn-light" title="Instagram" target="_blank" href="#"><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-icon btn-light" title="Youtube" target="_blank" href="#"><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-icon btn-light" title="Twitter" target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                            </div>
                        </article>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Sobre</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Sobre nós</a></li>
                            <li> <a href="#">Serviços</a></li>
                            <li> <a href="#">Termo de Uso</a></li>
                            <li> <a href="#">FAQ</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Serviços</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Meus Pedidos</a></li>
                            <li> <a href="#">Meu Perfil</a></li>
                            <li> <a href="#">Cancelamentos</a></li>
                            <li> <a href="#">Reembolsos</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-2  col-md-2">
                        <h6 class="title">Mobile</h6>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/appstore.png" height="40"></a>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/playmarket.png" height="40"></a>
                    </aside>
                </div>   
            </section>	  

            <section class="footer-copyright border-top">
                <p class="float-left text-muted"> Nerd Store Enterprise </p>
                <p class="float-right text-muted">
                    Material do curso ASP.NET Core Enterprise Applications - 
                    <a target="_blank" href="https://desenvolvedor.io">desenvolvedor.io</a>
                </p>
            </section>
        </div>  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="~/js/script.js" type="text/javascript"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>